-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_0_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_0_V_V_empty_n : IN STD_LOGIC;
    data_0_V_V_read : OUT STD_LOGIC;
    data_1_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_V_empty_n : IN STD_LOGIC;
    data_1_V_V_read : OUT STD_LOGIC;
    data_2_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_V_empty_n : IN STD_LOGIC;
    data_2_V_V_read : OUT STD_LOGIC;
    data_3_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_V_empty_n : IN STD_LOGIC;
    data_3_V_V_read : OUT STD_LOGIC;
    data_4_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_V_empty_n : IN STD_LOGIC;
    data_4_V_V_read : OUT STD_LOGIC;
    data_5_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_V_empty_n : IN STD_LOGIC;
    data_5_V_V_read : OUT STD_LOGIC;
    data_6_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_V_V_empty_n : IN STD_LOGIC;
    data_6_V_V_read : OUT STD_LOGIC;
    data_7_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_V_V_empty_n : IN STD_LOGIC;
    data_7_V_V_read : OUT STD_LOGIC;
    res_0_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_0_V_V_TVALID : OUT STD_LOGIC;
    res_0_V_V_TREADY : IN STD_LOGIC;
    res_1_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_1_V_V_TVALID : OUT STD_LOGIC;
    res_1_V_V_TREADY : IN STD_LOGIC;
    res_2_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_2_V_V_TVALID : OUT STD_LOGIC;
    res_2_V_V_TREADY : IN STD_LOGIC;
    res_3_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_3_V_V_TVALID : OUT STD_LOGIC;
    res_3_V_V_TREADY : IN STD_LOGIC;
    res_4_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_4_V_V_TVALID : OUT STD_LOGIC;
    res_4_V_V_TREADY : IN STD_LOGIC;
    res_5_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_5_V_V_TVALID : OUT STD_LOGIC;
    res_5_V_V_TREADY : IN STD_LOGIC;
    res_6_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_6_V_V_TVALID : OUT STD_LOGIC;
    res_6_V_V_TREADY : IN STD_LOGIC;
    res_7_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_7_V_V_TVALID : OUT STD_LOGIC;
    res_7_V_V_TREADY : IN STD_LOGIC );
end;


architecture behav of conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv7_48 : STD_LOGIC_VECTOR (6 downto 0) := "1001000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_F : STD_LOGIC_VECTOR (10 downto 0) := "00000001111";
    constant ap_const_lv32_47F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010001111111";
    constant ap_const_lv11_47F : STD_LOGIC_VECTOR (10 downto 0) := "10001111111";
    constant ap_const_lv1152_lc_2 : STD_LOGIC_VECTOR (1151 downto 0) := "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_72 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal layer_in_V : STD_LOGIC_VECTOR (1151 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal sX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal w2_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal w2_V_ce0 : STD_LOGIC;
    signal w2_V_q0 : STD_LOGIC_VECTOR (114 downto 0);
    signal data_0_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal data_1_V_V_blk_n : STD_LOGIC;
    signal data_2_V_V_blk_n : STD_LOGIC;
    signal data_3_V_V_blk_n : STD_LOGIC;
    signal data_4_V_V_blk_n : STD_LOGIC;
    signal data_5_V_V_blk_n : STD_LOGIC;
    signal data_6_V_V_blk_n : STD_LOGIC;
    signal data_7_V_V_blk_n : STD_LOGIC;
    signal res_0_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal and_ln176_2_reg_1234 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_1_V_V_TDATA_blk_n : STD_LOGIC;
    signal res_2_V_V_TDATA_blk_n : STD_LOGIC;
    signal res_3_V_V_TDATA_blk_n : STD_LOGIC;
    signal res_4_V_V_TDATA_blk_n : STD_LOGIC;
    signal res_5_V_V_TDATA_blk_n : STD_LOGIC;
    signal res_6_V_V_TDATA_blk_n : STD_LOGIC;
    signal res_7_V_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_V_22_reg_436 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_21_reg_449 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_20_reg_462 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_19_reg_475 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_18_reg_488 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_17_reg_501 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_16_reg_514 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_15_reg_527 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_index_reg_540 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i_fu_696_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_reg_1212 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal regslice_both_res_0_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_1_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_2_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_3_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_4_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_5_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_6_V_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_7_V_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_return : STD_LOGIC_VECTOR (1151 downto 0);
    signal call_ret_reg_1217 : STD_LOGIC_VECTOR (1151 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal icmp_ln176_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln176_reg_1224 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln176_1_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln176_1_reg_1229 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln176_2_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_reg_1238 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln74_reg_1238_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ir_fu_797_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln83_fu_905_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln83_reg_1247 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_0_V_reg_1264 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_1_V_reg_1269 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_2_V_reg_1274 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_3_V_reg_1279 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_4_V_reg_1284 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_5_V_reg_1289 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_6_V_reg_1294 : STD_LOGIC_VECTOR (15 downto 0);
    signal op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal op_V_assign_2_0_7_reg_1299 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_0_V_fu_1000_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal acc_1_V_fu_1005_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_2_V_fu_1010_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_3_V_fu_1015_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_4_V_fu_1020_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_5_V_fu_1025_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_6_V_fu_1030_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal acc_7_V_fu_1035_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln198_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln198_reg_1344 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_start : STD_LOGIC;
    signal call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_done : STD_LOGIC;
    signal call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_idle : STD_LOGIC;
    signal call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_ready : STD_LOGIC;
    signal call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_data_V_read : STD_LOGIC_VECTOR (127 downto 0);
    signal tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_ap_ready : STD_LOGIC;
    signal tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_ap_ready : STD_LOGIC;
    signal tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_ap_ready : STD_LOGIC;
    signal tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_ap_ready : STD_LOGIC;
    signal tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_ap_ready : STD_LOGIC;
    signal tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_ap_ready : STD_LOGIC;
    signal tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_ap_ready : STD_LOGIC;
    signal tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_ap_ready : STD_LOGIC;
    signal op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_w_V : STD_LOGIC_VECTOR (15 downto 0);
    signal layer_in_V_loc_0_reg_415 : STD_LOGIC_VECTOR (1151 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal i_0_i_reg_425 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state3_ignore_call13 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln83_fu_909_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln213_fu_1064_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln206_fu_1105_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln202_fu_1099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln211_fu_1046_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal pX_loc_0_fu_282 : STD_LOGIC_VECTOR (31 downto 0);
    signal sX_loc_0_fu_286 : STD_LOGIC_VECTOR (31 downto 0);
    signal pY_loc_0_fu_290 : STD_LOGIC_VECTOR (31 downto 0);
    signal sY_loc_0_fu_294 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln208_fu_1123_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state7_io : BOOLEAN;
    signal tmp_3_fu_741_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_4_fu_757_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln176_2_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln176_3_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln176_1_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln176_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_803_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_28_fu_811_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln83_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln83_fu_832_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln83_2_fu_844_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_823_p4 : STD_LOGIC_VECTOR (1151 downto 0);
    signal sub_ln83_1_fu_838_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln83_fu_850_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln83_2_fu_865_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln83_3_fu_873_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln83_1_fu_858_p3 : STD_LOGIC_VECTOR (1151 downto 0);
    signal zext_ln83_2_fu_879_p1 : STD_LOGIC_VECTOR (1151 downto 0);
    signal zext_ln83_3_fu_883_p1 : STD_LOGIC_VECTOR (1151 downto 0);
    signal lshr_ln83_fu_887_p2 : STD_LOGIC_VECTOR (1151 downto 0);
    signal lshr_ln83_1_fu_893_p2 : STD_LOGIC_VECTOR (1151 downto 0);
    signal and_ln83_fu_899_p2 : STD_LOGIC_VECTOR (1151 downto 0);
    signal tmp_2_fu_985_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln213_fu_1058_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln208_fu_1117_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln167_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal res_0_V_V_TVALID_int : STD_LOGIC;
    signal res_0_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_0_V_V_U_vld_out : STD_LOGIC;
    signal res_1_V_V_TVALID_int : STD_LOGIC;
    signal res_1_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_1_V_V_U_vld_out : STD_LOGIC;
    signal res_2_V_V_TVALID_int : STD_LOGIC;
    signal res_2_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_2_V_V_U_vld_out : STD_LOGIC;
    signal res_3_V_V_TVALID_int : STD_LOGIC;
    signal res_3_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_3_V_V_U_vld_out : STD_LOGIC;
    signal res_4_V_V_TVALID_int : STD_LOGIC;
    signal res_4_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_4_V_V_U_vld_out : STD_LOGIC;
    signal res_5_V_V_TVALID_int : STD_LOGIC;
    signal res_5_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_5_V_V_U_vld_out : STD_LOGIC;
    signal res_6_V_V_TVALID_int : STD_LOGIC;
    signal res_6_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_6_V_V_U_vld_out : STD_LOGIC;
    signal res_7_V_V_TVALID_int : STD_LOGIC;
    signal res_7_V_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_7_V_V_U_vld_out : STD_LOGIC;
    signal ap_condition_418 : BOOLEAN;

    component cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V_read : IN STD_LOGIC_VECTOR (127 downto 0);
        output_V_read : IN STD_LOGIC_VECTOR (1151 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (1151 downto 0) );
    end component;


    component product_dense_ap_fixed_ap_fixed_ap_fixed_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        a_V : IN STD_LOGIC_VECTOR (15 downto 0);
        w_V : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_w2_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (114 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    w2_V_U : component conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_w2_V
    generic map (
        DataWidth => 115,
        AddressRange => 72,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w2_V_address0,
        ce0 => w2_V_ce0,
        q0 => w2_V_q0);

    call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551 : component cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_start,
        ap_done => call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_done,
        ap_idle => call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_idle,
        ap_ready => call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_ready,
        data_V_read => call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_data_V_read,
        output_V_read => layer_in_V_loc_0_reg_415,
        ap_return => call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_return);

    tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_w_V,
        ap_return => tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_ap_return);

    tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_w_V,
        ap_return => tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_ap_return);

    tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_w_V,
        ap_return => tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_ap_return);

    tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_w_V,
        ap_return => tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_ap_return);

    tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_w_V,
        ap_return => tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_ap_return);

    tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_w_V,
        ap_return => tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_ap_return);

    tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_w_V,
        ap_return => tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_ap_return);

    op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632 : component product_dense_ap_fixed_ap_fixed_ap_fixed_s
    port map (
        ap_ready => op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_ap_ready,
        a_V => trunc_ln83_reg_1247,
        w_V => op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_w_V,
        ap_return => op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_ap_return);

    regslice_both_res_0_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_15_reg_527,
        vld_in => res_0_V_V_TVALID_int,
        ack_in => res_0_V_V_TREADY_int,
        data_out => res_0_V_V_TDATA,
        vld_out => regslice_both_res_0_V_V_U_vld_out,
        ack_out => res_0_V_V_TREADY,
        apdone_blk => regslice_both_res_0_V_V_U_apdone_blk);

    regslice_both_res_1_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_16_reg_514,
        vld_in => res_1_V_V_TVALID_int,
        ack_in => res_1_V_V_TREADY_int,
        data_out => res_1_V_V_TDATA,
        vld_out => regslice_both_res_1_V_V_U_vld_out,
        ack_out => res_1_V_V_TREADY,
        apdone_blk => regslice_both_res_1_V_V_U_apdone_blk);

    regslice_both_res_2_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_17_reg_501,
        vld_in => res_2_V_V_TVALID_int,
        ack_in => res_2_V_V_TREADY_int,
        data_out => res_2_V_V_TDATA,
        vld_out => regslice_both_res_2_V_V_U_vld_out,
        ack_out => res_2_V_V_TREADY,
        apdone_blk => regslice_both_res_2_V_V_U_apdone_blk);

    regslice_both_res_3_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_18_reg_488,
        vld_in => res_3_V_V_TVALID_int,
        ack_in => res_3_V_V_TREADY_int,
        data_out => res_3_V_V_TDATA,
        vld_out => regslice_both_res_3_V_V_U_vld_out,
        ack_out => res_3_V_V_TREADY,
        apdone_blk => regslice_both_res_3_V_V_U_apdone_blk);

    regslice_both_res_4_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_19_reg_475,
        vld_in => res_4_V_V_TVALID_int,
        ack_in => res_4_V_V_TREADY_int,
        data_out => res_4_V_V_TDATA,
        vld_out => regslice_both_res_4_V_V_U_vld_out,
        ack_out => res_4_V_V_TREADY,
        apdone_blk => regslice_both_res_4_V_V_U_apdone_blk);

    regslice_both_res_5_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_20_reg_462,
        vld_in => res_5_V_V_TVALID_int,
        ack_in => res_5_V_V_TREADY_int,
        data_out => res_5_V_V_TDATA,
        vld_out => regslice_both_res_5_V_V_U_vld_out,
        ack_out => res_5_V_V_TREADY,
        apdone_blk => regslice_both_res_5_V_V_U_apdone_blk);

    regslice_both_res_6_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_21_reg_449,
        vld_in => res_6_V_V_TVALID_int,
        ack_in => res_6_V_V_TREADY_int,
        data_out => res_6_V_V_TDATA,
        vld_out => regslice_both_res_6_V_V_U_vld_out,
        ack_out => res_6_V_V_TREADY,
        apdone_blk => regslice_both_res_6_V_V_U_apdone_blk);

    regslice_both_res_7_V_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_V_22_reg_436,
        vld_in => res_7_V_V_TVALID_int,
        ack_in => res_7_V_V_TREADY_int,
        data_out => res_7_V_V_TDATA,
        vld_out => regslice_both_res_7_V_V_U_vld_out,
        ack_out => res_7_V_V_TREADY,
        apdone_blk => regslice_both_res_7_V_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln167_fu_690_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_0_i_reg_425_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                i_0_i_reg_425 <= i_reg_1212;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_i_reg_425 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    in_index_reg_540_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln74_fu_791_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                in_index_reg_540 <= ir_fu_797_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                in_index_reg_540 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    layer_in_V_loc_0_reg_415_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                layer_in_V_loc_0_reg_415 <= call_ret_reg_1217;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                layer_in_V_loc_0_reg_415 <= layer_in_V;
            end if; 
        end if;
    end process;

    pX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                if ((icmp_ln198_fu_1040_p2 = ap_const_lv1_1)) then 
                    pX <= ap_const_lv32_0;
                elsif ((icmp_ln198_fu_1040_p2 = ap_const_lv1_0)) then 
                    pX <= add_ln211_fu_1046_p2;
                end if;
            end if; 
        end if;
    end process;

    pX_loc_0_fu_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln198_reg_1344 = ap_const_lv1_1))) then 
                pX_loc_0_fu_282 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_state8_io) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                pX_loc_0_fu_282 <= add_ln211_fu_1046_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                pX_loc_0_fu_282 <= pX;
            end if; 
        end if;
    end process;

    pY_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_418)) then
                if ((icmp_ln202_fu_1099_p2 = ap_const_lv1_1)) then 
                    pY <= ap_const_lv32_0;
                elsif ((icmp_ln202_fu_1099_p2 = ap_const_lv1_0)) then 
                    pY <= add_ln206_fu_1105_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_loc_0_fu_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln202_fu_1099_p2 = ap_const_lv1_1) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_1))) then 
                pY_loc_0_fu_290 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_state8_io) and (icmp_ln202_fu_1099_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_1))) then 
                pY_loc_0_fu_290 <= add_ln206_fu_1105_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                pY_loc_0_fu_290 <= pY;
            end if; 
        end if;
    end process;

    sX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                if ((icmp_ln198_fu_1040_p2 = ap_const_lv1_1)) then 
                    sX <= ap_const_lv32_0;
                elsif ((icmp_ln198_fu_1040_p2 = ap_const_lv1_0)) then 
                    sX <= select_ln213_fu_1064_p3;
                end if;
            end if; 
        end if;
    end process;

    sX_loc_0_fu_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln198_reg_1344 = ap_const_lv1_1))) then 
                sX_loc_0_fu_286 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_state8_io) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                sX_loc_0_fu_286 <= select_ln213_fu_1064_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sX_loc_0_fu_286 <= sX;
            end if; 
        end if;
    end process;

    sY_loc_0_fu_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln202_fu_1099_p2 = ap_const_lv1_1) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_1))) then 
                sY_loc_0_fu_294 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_state8_io) and (icmp_ln202_fu_1099_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_1))) then 
                sY_loc_0_fu_294 <= select_ln208_fu_1123_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sY_loc_0_fu_294 <= sY;
            end if; 
        end if;
    end process;

    tmp_V_15_reg_527_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_15_reg_527 <= acc_0_V_fu_1000_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_15_reg_527 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_16_reg_514_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_16_reg_514 <= acc_1_V_fu_1005_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_16_reg_514 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_17_reg_501_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_17_reg_501 <= acc_2_V_fu_1010_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_17_reg_501 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_18_reg_488_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_18_reg_488 <= acc_3_V_fu_1015_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_18_reg_488 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_19_reg_475_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_19_reg_475 <= acc_4_V_fu_1020_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_19_reg_475 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_20_reg_462_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_20_reg_462 <= acc_5_V_fu_1025_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_20_reg_462 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_21_reg_449_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_21_reg_449 <= acc_6_V_fu_1030_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_21_reg_449 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    tmp_V_22_reg_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_reg_1238_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                tmp_V_22_reg_436 <= acc_7_V_fu_1035_p2;
            elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then 
                tmp_V_22_reg_436 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                and_ln176_2_reg_1234 <= and_ln176_2_fu_785_p2;
                call_ret_reg_1217 <= call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_return;
                icmp_ln176_1_reg_1229 <= icmp_ln176_1_fu_735_p2;
                icmp_ln176_reg_1224 <= icmp_ln176_fu_729_p2;
                layer_in_V <= call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_1212 <= i_fu_696_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                icmp_ln198_reg_1344 <= icmp_ln198_fu_1040_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln74_reg_1238 <= icmp_ln74_fu_791_p2;
                icmp_ln74_reg_1238_pp0_iter1_reg <= icmp_ln74_reg_1238;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln74_reg_1238 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                op_V_assign_2_0_7_reg_1299 <= op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_ap_return;
                tmpmult_0_V_reg_1264 <= tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_ap_return;
                tmpmult_1_V_reg_1269 <= tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_ap_return;
                tmpmult_2_V_reg_1274 <= tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_ap_return;
                tmpmult_3_V_reg_1279 <= tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_ap_return;
                tmpmult_4_V_reg_1284 <= tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_ap_return;
                tmpmult_5_V_reg_1289 <= tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_ap_return;
                tmpmult_6_V_reg_1294 <= tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln198_reg_1344 = ap_const_lv1_1))) then
                sY <= sY_loc_0_fu_294;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln74_fu_791_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln83_reg_1247 <= trunc_ln83_fu_905_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state2, regslice_both_res_0_V_V_U_apdone_blk, regslice_both_res_1_V_V_U_apdone_blk, regslice_both_res_2_V_V_U_apdone_blk, regslice_both_res_3_V_V_U_apdone_blk, regslice_both_res_4_V_V_U_apdone_blk, regslice_both_res_5_V_V_U_apdone_blk, regslice_both_res_6_V_V_U_apdone_blk, regslice_both_res_7_V_V_U_apdone_blk, and_ln176_2_fu_785_p2, icmp_ln74_fu_791_p2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_state8_io, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_block_state7_io, icmp_ln167_fu_690_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln167_fu_690_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1))) and (icmp_ln167_fu_690_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv1_1 = and_ln176_2_fu_785_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_lv1_0 = and_ln176_2_fu_785_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln74_fu_791_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln74_fu_791_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    acc_0_V_fu_1000_p2 <= std_logic_vector(unsigned(tmpmult_0_V_reg_1264) + unsigned(tmp_V_15_reg_527));
    acc_1_V_fu_1005_p2 <= std_logic_vector(unsigned(tmpmult_1_V_reg_1269) + unsigned(tmp_V_16_reg_514));
    acc_2_V_fu_1010_p2 <= std_logic_vector(unsigned(tmpmult_2_V_reg_1274) + unsigned(tmp_V_17_reg_501));
    acc_3_V_fu_1015_p2 <= std_logic_vector(unsigned(tmpmult_3_V_reg_1279) + unsigned(tmp_V_18_reg_488));
    acc_4_V_fu_1020_p2 <= std_logic_vector(unsigned(tmpmult_4_V_reg_1284) + unsigned(tmp_V_19_reg_475));
    acc_5_V_fu_1025_p2 <= std_logic_vector(unsigned(tmpmult_5_V_reg_1289) + unsigned(tmp_V_20_reg_462));
    acc_6_V_fu_1030_p2 <= std_logic_vector(unsigned(tmpmult_6_V_reg_1294) + unsigned(tmp_V_21_reg_449));
    acc_7_V_fu_1035_p2 <= std_logic_vector(unsigned(op_V_assign_2_0_7_reg_1299) + unsigned(tmp_V_22_reg_436));
    add_ln206_fu_1105_p2 <= std_logic_vector(unsigned(pY_loc_0_fu_290) + unsigned(ap_const_lv32_1));
    add_ln208_fu_1117_p2 <= std_logic_vector(unsigned(sY_loc_0_fu_294) + unsigned(ap_const_lv32_1));
    add_ln211_fu_1046_p2 <= std_logic_vector(unsigned(pX_loc_0_fu_282) + unsigned(ap_const_lv32_1));
    add_ln213_fu_1058_p2 <= std_logic_vector(unsigned(sX_loc_0_fu_286) + unsigned(ap_const_lv32_1));
    and_ln176_1_fu_779_p2 <= (icmp_ln176_3_fu_767_p2 and icmp_ln176_2_fu_751_p2);
    and_ln176_2_fu_785_p2 <= (and_ln176_fu_773_p2 and and_ln176_1_fu_779_p2);
    and_ln176_fu_773_p2 <= (icmp_ln176_fu_729_p2 and icmp_ln176_1_fu_735_p2);
    and_ln83_fu_899_p2 <= (lshr_ln83_fu_887_p2 and lshr_ln83_1_fu_893_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(4);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);
    ap_CS_fsm_state9 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(regslice_both_res_0_V_V_U_apdone_blk, regslice_both_res_1_V_V_U_apdone_blk, regslice_both_res_2_V_V_U_apdone_blk, regslice_both_res_3_V_V_U_apdone_blk, regslice_both_res_4_V_V_U_apdone_blk, regslice_both_res_5_V_V_U_apdone_blk, regslice_both_res_6_V_V_U_apdone_blk, regslice_both_res_7_V_V_U_apdone_blk)
    begin
                ap_block_state2 <= ((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n)
    begin
                ap_block_state3 <= ((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_ignore_call13_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n)
    begin
                ap_block_state3_ignore_call13 <= ((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_io_assign_proc : process(res_0_V_V_TREADY_int, res_1_V_V_TREADY_int, res_2_V_V_TREADY_int, res_3_V_V_TREADY_int, res_4_V_V_TREADY_int, res_5_V_V_TREADY_int, res_6_V_V_TREADY_int, res_7_V_V_TREADY_int)
    begin
                ap_block_state7_io <= ((res_7_V_V_TREADY_int = ap_const_logic_0) or (res_6_V_V_TREADY_int = ap_const_logic_0) or (res_5_V_V_TREADY_int = ap_const_logic_0) or (res_4_V_V_TREADY_int = ap_const_logic_0) or (res_3_V_V_TREADY_int = ap_const_logic_0) or (res_2_V_V_TREADY_int = ap_const_logic_0) or (res_1_V_V_TREADY_int = ap_const_logic_0) or (res_0_V_V_TREADY_int = ap_const_logic_0));
    end process;


    ap_block_state8_io_assign_proc : process(and_ln176_2_reg_1234, res_0_V_V_TREADY_int, res_1_V_V_TREADY_int, res_2_V_V_TREADY_int, res_3_V_V_TREADY_int, res_4_V_V_TREADY_int, res_5_V_V_TREADY_int, res_6_V_V_TREADY_int, res_7_V_V_TREADY_int)
    begin
                ap_block_state8_io <= (((res_7_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_6_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_5_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_4_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_3_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_2_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_1_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)) or ((res_0_V_V_TREADY_int = ap_const_logic_0) and (ap_const_lv1_1 = and_ln176_2_reg_1234)));
    end process;


    ap_condition_418_assign_proc : process(ap_CS_fsm_state8, icmp_ln198_fu_1040_p2, ap_block_state8_io)
    begin
                ap_condition_418 <= ((ap_const_boolean_0 = ap_block_state8_io) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln198_fu_1040_p2 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter0_state4_assign_proc : process(icmp_ln74_fu_791_p2)
    begin
        if ((icmp_ln74_fu_791_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, regslice_both_res_0_V_V_U_apdone_blk, regslice_both_res_1_V_V_U_apdone_blk, regslice_both_res_2_V_V_U_apdone_blk, regslice_both_res_3_V_V_U_apdone_blk, regslice_both_res_4_V_V_U_apdone_blk, regslice_both_res_5_V_V_U_apdone_blk, regslice_both_res_6_V_V_U_apdone_blk, regslice_both_res_7_V_V_U_apdone_blk, icmp_ln167_fu_690_p2)
    begin
        if ((not(((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln167_fu_690_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, regslice_both_res_0_V_V_U_apdone_blk, regslice_both_res_1_V_V_U_apdone_blk, regslice_both_res_2_V_V_U_apdone_blk, regslice_both_res_3_V_V_U_apdone_blk, regslice_both_res_4_V_V_U_apdone_blk, regslice_both_res_5_V_V_U_apdone_blk, regslice_both_res_6_V_V_U_apdone_blk, regslice_both_res_7_V_V_U_apdone_blk, icmp_ln167_fu_690_p2)
    begin
        if ((not(((regslice_both_res_7_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_6_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_5_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_4_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_3_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_2_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_1_V_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_0_V_V_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln167_fu_690_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_start_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_start <= ap_const_logic_1;
        else 
            call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    call_ret_cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_fu_551_data_V_read <= (((((((data_7_V_V_dout & data_6_V_V_dout) & data_5_V_V_dout) & data_4_V_V_dout) & data_3_V_V_dout) & data_2_V_V_dout) & data_1_V_V_dout) & data_0_V_V_dout);

    data_0_V_V_blk_n_assign_proc : process(data_0_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_0_V_V_blk_n <= data_0_V_V_empty_n;
        else 
            data_0_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_0_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_0_V_V_read <= ap_const_logic_1;
        else 
            data_0_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_1_V_V_blk_n_assign_proc : process(data_1_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_1_V_V_blk_n <= data_1_V_V_empty_n;
        else 
            data_1_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_1_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_1_V_V_read <= ap_const_logic_1;
        else 
            data_1_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_2_V_V_blk_n_assign_proc : process(data_2_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_2_V_V_blk_n <= data_2_V_V_empty_n;
        else 
            data_2_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_2_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_2_V_V_read <= ap_const_logic_1;
        else 
            data_2_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_3_V_V_blk_n_assign_proc : process(data_3_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_3_V_V_blk_n <= data_3_V_V_empty_n;
        else 
            data_3_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_3_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_3_V_V_read <= ap_const_logic_1;
        else 
            data_3_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_4_V_V_blk_n_assign_proc : process(data_4_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_4_V_V_blk_n <= data_4_V_V_empty_n;
        else 
            data_4_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_4_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_4_V_V_read <= ap_const_logic_1;
        else 
            data_4_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_5_V_V_blk_n_assign_proc : process(data_5_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_5_V_V_blk_n <= data_5_V_V_empty_n;
        else 
            data_5_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_5_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_5_V_V_read <= ap_const_logic_1;
        else 
            data_5_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_6_V_V_blk_n_assign_proc : process(data_6_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_6_V_V_blk_n <= data_6_V_V_empty_n;
        else 
            data_6_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_6_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_6_V_V_read <= ap_const_logic_1;
        else 
            data_6_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_7_V_V_blk_n_assign_proc : process(data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_7_V_V_blk_n <= data_7_V_V_empty_n;
        else 
            data_7_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_7_V_V_read_assign_proc : process(data_0_V_V_empty_n, data_1_V_V_empty_n, data_2_V_V_empty_n, data_3_V_V_empty_n, data_4_V_V_empty_n, data_5_V_V_empty_n, data_6_V_V_empty_n, data_7_V_V_empty_n, ap_CS_fsm_state3)
    begin
        if ((not(((data_7_V_V_empty_n = ap_const_logic_0) or (data_6_V_V_empty_n = ap_const_logic_0) or (data_5_V_V_empty_n = ap_const_logic_0) or (data_4_V_V_empty_n = ap_const_logic_0) or (data_3_V_V_empty_n = ap_const_logic_0) or (data_2_V_V_empty_n = ap_const_logic_0) or (data_1_V_V_empty_n = ap_const_logic_0) or (data_0_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_7_V_V_read <= ap_const_logic_1;
        else 
            data_7_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    empty_28_fu_811_p2 <= (tmp_1_fu_803_p3 or ap_const_lv11_F);
    i_fu_696_p2 <= std_logic_vector(unsigned(i_0_i_reg_425) + unsigned(ap_const_lv5_1));
    icmp_ln167_fu_690_p2 <= "1" when (i_0_i_reg_425 = ap_const_lv5_19) else "0";
    icmp_ln176_1_fu_735_p2 <= "1" when (sY_loc_0_fu_294 = ap_const_lv32_2) else "0";
    icmp_ln176_2_fu_751_p2 <= "1" when (signed(tmp_3_fu_741_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln176_3_fu_767_p2 <= "1" when (signed(tmp_4_fu_757_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln176_fu_729_p2 <= "1" when (sX_loc_0_fu_286 = ap_const_lv32_2) else "0";
    icmp_ln198_fu_1040_p2 <= "1" when (pX_loc_0_fu_282 = ap_const_lv32_4) else "0";
    icmp_ln202_fu_1099_p2 <= "1" when (pY_loc_0_fu_290 = ap_const_lv32_4) else "0";
    icmp_ln74_fu_791_p2 <= "1" when (in_index_reg_540 = ap_const_lv7_48) else "0";
    icmp_ln83_fu_817_p2 <= "1" when (unsigned(tmp_1_fu_803_p3) > unsigned(empty_28_fu_811_p2)) else "0";
    ir_fu_797_p2 <= std_logic_vector(unsigned(in_index_reg_540) + unsigned(ap_const_lv7_1));
    lshr_ln83_1_fu_893_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv1152_lc_2),to_integer(unsigned('0' & zext_ln83_3_fu_883_p1(31-1 downto 0)))));
    lshr_ln83_fu_887_p2 <= std_logic_vector(shift_right(unsigned(select_ln83_1_fu_858_p3),to_integer(unsigned('0' & zext_ln83_2_fu_879_p1(31-1 downto 0)))));
    op_V_assign_2_0_7_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_632_w_V <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_985_p4),16));

    res_0_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_0_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_0_V_V_TDATA_blk_n <= res_0_V_V_TREADY_int;
        else 
            res_0_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_0_V_V_TVALID <= regslice_both_res_0_V_V_U_vld_out;

    res_0_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_0_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_0_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_1_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_1_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_1_V_V_TDATA_blk_n <= res_1_V_V_TREADY_int;
        else 
            res_1_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_1_V_V_TVALID <= regslice_both_res_1_V_V_U_vld_out;

    res_1_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_1_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_1_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_2_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_2_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_2_V_V_TDATA_blk_n <= res_2_V_V_TREADY_int;
        else 
            res_2_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_2_V_V_TVALID <= regslice_both_res_2_V_V_U_vld_out;

    res_2_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_2_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_2_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_3_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_3_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_3_V_V_TDATA_blk_n <= res_3_V_V_TREADY_int;
        else 
            res_3_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_3_V_V_TVALID <= regslice_both_res_3_V_V_U_vld_out;

    res_3_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_3_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_3_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_4_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_4_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_4_V_V_TDATA_blk_n <= res_4_V_V_TREADY_int;
        else 
            res_4_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_4_V_V_TVALID <= regslice_both_res_4_V_V_U_vld_out;

    res_4_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_4_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_4_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_5_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_5_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_5_V_V_TDATA_blk_n <= res_5_V_V_TREADY_int;
        else 
            res_5_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_5_V_V_TVALID <= regslice_both_res_5_V_V_U_vld_out;

    res_5_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_5_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_5_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_6_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_6_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_6_V_V_TDATA_blk_n <= res_6_V_V_TREADY_int;
        else 
            res_6_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_6_V_V_TVALID <= regslice_both_res_6_V_V_U_vld_out;

    res_6_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_6_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_6_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_7_V_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state8, and_ln176_2_reg_1234, res_7_V_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln176_2_reg_1234)))) then 
            res_7_V_V_TDATA_blk_n <= res_7_V_V_TREADY_int;
        else 
            res_7_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_7_V_V_TVALID <= regslice_both_res_7_V_V_U_vld_out;

    res_7_V_V_TVALID_int_assign_proc : process(ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state7_io) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            res_7_V_V_TVALID_int <= ap_const_logic_1;
        else 
            res_7_V_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    select_ln208_fu_1123_p3 <= 
        ap_const_lv32_2 when (icmp_ln176_1_reg_1229(0) = '1') else 
        add_ln208_fu_1117_p2;
    select_ln213_fu_1064_p3 <= 
        ap_const_lv32_2 when (icmp_ln176_reg_1224(0) = '1') else 
        add_ln213_fu_1058_p2;
    select_ln83_1_fu_858_p3 <= 
        tmp_10_fu_823_p4 when (icmp_ln83_fu_817_p2(0) = '1') else 
        call_ret_reg_1217;
    select_ln83_2_fu_865_p3 <= 
        sub_ln83_1_fu_838_p2 when (icmp_ln83_fu_817_p2(0) = '1') else 
        tmp_1_fu_803_p3;
    select_ln83_fu_850_p3 <= 
        sub_ln83_fu_832_p2 when (icmp_ln83_fu_817_p2(0) = '1') else 
        sub_ln83_2_fu_844_p2;
    sub_ln83_1_fu_838_p2 <= std_logic_vector(signed(ap_const_lv11_47F) - signed(tmp_1_fu_803_p3));
    sub_ln83_2_fu_844_p2 <= std_logic_vector(unsigned(empty_28_fu_811_p2) - unsigned(tmp_1_fu_803_p3));
    sub_ln83_3_fu_873_p2 <= std_logic_vector(signed(ap_const_lv11_47F) - signed(select_ln83_fu_850_p3));
    sub_ln83_fu_832_p2 <= std_logic_vector(unsigned(tmp_1_fu_803_p3) - unsigned(empty_28_fu_811_p2));
    
    tmp_10_fu_823_p4_proc : process(call_ret_reg_1217)
    variable vlo_cpy : STD_LOGIC_VECTOR(1152+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(1152+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(1152 - 1 downto 0);
    variable tmp_10_fu_823_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(1152 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(1152 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(1152 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(11 - 1 downto 0) := ap_const_lv32_47F(11 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(11 - 1 downto 0) := ap_const_lv32_0(11 - 1 downto 0);
        v0_cpy := call_ret_reg_1217;
        if (vlo_cpy(11 - 1 downto 0) > vhi_cpy(11 - 1 downto 0)) then
            vhi_cpy(11-1 downto 0) := std_logic_vector(1152-1-unsigned(ap_const_lv32_0(11-1 downto 0)));
            vlo_cpy(11-1 downto 0) := std_logic_vector(1152-1-unsigned(ap_const_lv32_47F(11-1 downto 0)));
            for tmp_10_fu_823_p4_i in 0 to 1152-1 loop
                v0_cpy(tmp_10_fu_823_p4_i) := call_ret_reg_1217(1152-1-tmp_10_fu_823_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(11-1 downto 0)))));

        section := (others=>'0');
        section(11-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(11-1 downto 0)) - unsigned(vlo_cpy(11-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(1152-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_10_fu_823_p4 <= resvalue(1152-1 downto 0);
    end process;

    tmp_1_fu_803_p3 <= (in_index_reg_540 & ap_const_lv4_0);
    tmp_2_fu_985_p4 <= w2_V_q0(114 downto 112);
    tmp_3_fu_741_p4 <= pY_loc_0_fu_290(31 downto 1);
    tmp_4_fu_757_p4 <= pX_loc_0_fu_282(31 downto 1);
    tmpmult_0_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_590_w_V <= w2_V_q0(16 - 1 downto 0);
    tmpmult_1_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_596_w_V <= w2_V_q0(31 downto 16);
    tmpmult_2_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_602_w_V <= w2_V_q0(47 downto 32);
    tmpmult_3_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_608_w_V <= w2_V_q0(63 downto 48);
    tmpmult_4_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_614_w_V <= w2_V_q0(79 downto 64);
    tmpmult_5_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_620_w_V <= w2_V_q0(95 downto 80);
    tmpmult_6_V_product_dense_ap_fixed_ap_fixed_ap_fixed_s_fu_626_w_V <= w2_V_q0(111 downto 96);
    trunc_ln83_fu_905_p1 <= and_ln83_fu_899_p2(16 - 1 downto 0);
    w2_V_address0 <= zext_ln83_fu_909_p1(7 - 1 downto 0);

    w2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w2_V_ce0 <= ap_const_logic_1;
        else 
            w2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln83_2_fu_879_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln83_2_fu_865_p3),1152));
    zext_ln83_3_fu_883_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln83_3_fu_873_p2),1152));
    zext_ln83_fu_909_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_index_reg_540),64));
end behav;
